<template>
    <div class="w-full flex flex-row justify-start h-full">
        <div class="h-full"></div>
        <n-layout-sider
            bordered
            :width="310"
            show-trigger="bar"
            :collapsed-width="20"
            class="h-full"
        >
            <div class="flex flex-col h-full">
                <div class="h-1/8 flex flex-row justify-start items-center w-full">
                    <div class="font-500 text-[28px] text-[#3e5294] ml-18">Directly Start</div>
                </div>
                <div class="h-2/8 flex flex-col justify-center items-center">
                    <el-button round color="#34498E" class="w-30 h-9" @click="goDocument">
                        Help
                    </el-button>
                    <img src="../../public/png/help.png" class="image w-34 h-23 mt-2" />
                </div>
                <div class="h-2/8 flex flex-col justify-center items-center">
                    <el-button round color="#34498E" class="w-30 h-9" @click="godatabasae">
                        Database
                    </el-button>
                    <img src="../../public/png/database.png" class="image w-34 h-34" />
                </div>
                <div class="h-2/8 flex flex-col justify-center items-center">
                    <el-button round color="#34498E" class="w-30 h-9" @click="goAnalysis">
                        Analysis
                    </el-button>
                    <img src="../../public/png/analysis.png" class="image w-34 h-34" />
                </div>
            </div>
        </n-layout-sider>

        <el-scrollbar ref="scrollbarRef" class="w-full">
            <div class="w-full flex flex-col justify-start h-700 bg-[#f8f9fa]">
                <div class="h-220 flex flex-col">
                    <div class="flex flex-row border-b-1 border-[#34498E] ml-13 w-290 pb-6">
                        <div class="text-5xl font-700 mt-20 text-[#3e5294]">CyGraph</div>
                        <el-button
                            round
                            color="#34498E"
                            class="w-25 h-7 mt-24 ml-10"
                            @click="godatabasae"
                        >
                            Database
                        </el-button>
                        <el-button
                            round
                            color="#34498E"
                            class="w-25 h-7 mt-24 ml-18"
                            @click="goAnalysis"
                        >
                            Analysis
                        </el-button>
                    </div>

                    <div class="text-[22px] font-400 mt-13 ml-15 w-[84%] leading-9 text-gray-900">
                        Welcome to
                        <strong class="text-2xl font-600 text-[#ee7e7d] ml-1">CyGraph</strong>
                        , the dedicated database for
                        <strong class="text-2xl font-600 text-[#ee7e7d] ml-1">Cytocraft</strong>
                        results.
                        <strong class="text-2xl font-600 text-[#ee7e7d] ml-1">Cytocraft</strong>
                        , a cutting-edge method in the field of spatial transcriptomics, offers
                        unparalleled insights into chromosome conformation. Our database,
                        <strong class="text-2xl font-600 text-[#ee7e7d] ml-1">CyGraph</strong>
                        , is designed to be the central repository for data generated by this
                        innovative technique.
                    </div>
                    <div class="text-[22px] font-400 mt-13 ml-15 w-[84%] leading-9 text-gray-900">
                        At
                        <strong class="text-2xl font-600 text-[#ee7e7d] ml-1">CyGraph</strong>
                        , we understand the importance of accessibility and organization when it
                        comes to scientific data. That's why we've created a user-friendly platform
                        that not only stores but also allows for efficient querying and analysis of
                        Cytocraft results. Whether you're a researcher looking to compare findings
                        or a student delving into the world of spatial transcriptomics,
                        <strong class="text-2xl font-600 text-[#ee7e7d] ml-1">CyGraph</strong>
                        is your go-to resource.
                    </div>
                    <div class="text-[22px] font-400 mt-13 ml-15 w-[84%] leading-9 text-gray-900">
                        Join us in exploring the intricate details of cellular architecture, made
                        possible by the pioneering Cytocraft method. Dive into our database and
                        discover the potential of spatially resolved chromosomal interactions in
                        advancing our understanding of genetic regulation and expression.
                    </div>
                </div>
                <div class="h-240 flex flex-col items-center">
                    <div class="mb-10 text-3xl font-600 text-[#3e5294] mt-25">Focus</div>
                    <div
                        style="box-shadow: 0 0 64px #cfd5db"
                        class="w-270 h-150 bg-white rounded-2xl"
                    >
                        <div>
                            <el-carousel
                                height="600px"
                                width="1080px"
                                arrow="always"
                                indicator-position="outside"
                                :autoplay="false"
                            >
                                <el-carousel-item>
                                    <div class="w-270 h-150">
                                        <el-image
                                            src="/png/databasevis.png"
                                            class="image w-270 h-150"
                                            z-index="100"
                                        />
                                    </div>
                                </el-carousel-item>
                                <el-carousel-item>
                                    <div
                                        class="w-270 h-150 flex flex-row items-center justify-center"
                                    >
                                        <el-image
                                            src="/png/analysisvis.png"
                                            class="image w-270 h-150"
                                            z-index="100"
                                        />
                                    </div>
                                </el-carousel-item>
                                <el-carousel-item>
                                    <div
                                        class="w-270 h-150 flex flex-row items-center justify-center"
                                    >
                                        <el-image
                                            src="/png/visualization.png"
                                            class="image w-270 h-150"
                                            z-index="100"
                                        />
                                    </div>
                                </el-carousel-item>
                            </el-carousel>
                        </div>
                    </div>
                </div>

                <div class="h-170 flex flex-row w-full justify-center mt-20">
                    <div class="w-270 flex flex-row">
                        <div>
                            <iframe class="w-120 h-120" src="/cloudTag.html"></iframe>
                        </div>
                        <el-scrollbar
                            class="w-110 h-100 ml-40 rounded-7px bg-white mt-10"
                            style="box-shadow: 0 0 64px #cfd5db"
                        >
                            <div class="text-3xl font-600 mt-4 ml-8">NEWS</div>

                            <el-steps direction="vertical" class="h-70 ml-8 mt-5 mb-10">
                                <el-step :icon="Opportunity" status="process">
                                    <template #title>
                                        <div class="text-gray-700 font-600">
                                            Notice (2023.11.07)
                                        </div>
                                    </template>
                                    <template #description>
                                        <div :class="descriptionClass">
                                            We are in the process of updating some data on our
                                            website, which may result in occasional issues or bugs.
                                            We are addressing these and anticipate a resolution
                                            within the next week.
                                        </div>
                                    </template>
                                </el-step>
                                <el-step :icon="Opportunity" status="process">
                                    <template #title>
                                        <div class="text-gray-700 font-600">
                                            Version 1.1 (2023.10.10)
                                        </div>
                                    </template>
                                    <template #description>
                                        <div :class="descriptionClass">
                                            Five additional phage datasets are incorporated into the
                                            database.
                                            <br />
                                            Update the genome comparison modules to provide the
                                            option to compare customized phage genomes with the
                                            PhageScope database.
                                        </div>
                                    </template>
                                </el-step>
                                <el-step :icon="Opportunity" status="process">
                                    <template #title>
                                        <div class="text-gray-700 font-600">
                                            Version 1.0 (2023.7.1)
                                        </div>
                                    </template>
                                    <template #description>
                                        <div :class="descriptionClass">
                                            PhageScope has been released. Welcome to use!
                                        </div>
                                    </template>
                                </el-step>
                            </el-steps>
                        </el-scrollbar>
                    </div>
                </div>
                <div class="flex flex-row w-full justify-center mb-10">
                    <div style="box-shadow: 0 0 64px #cfd5db" class="w-320 h-50 mb-10 rounded-7px">
                        <div class="text-[22px] px-9 py-2 leading-10 text-gray-700 bg-gray-300">
                            If you want to use PhageScope,
                            <strong class="text-[#ee7e7d] font-400 mx-1 text-[22px]">
                                <a
                                    href="https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkad979/7334092"
                                >
                                    please cite our publication.
                                </a>
                            </strong>
                        </div>
                        <div class="text-[18px] px-9 py-2 leading-10 text-gray-700">
                            Ruo Han Wang, Shuo Yang, Zhixuan Liu, Yuanzheng Zhang, Xueying Wang,
                            Zixin Xu, Jianping Wang, Shuai Cheng Li, PhageScope: a well-annotated
                            bacteriophage database with automatic analyses and visualizations,
                            Nucleic Acids Research, 2023;, gkad979,
                            https://doi.org/10.1093/nar/gkad979
                        </div>
                    </div>
                </div>
                <el-footer
                    class="px-20 h-70 bg-[#253959] flex flex-col justify-center items-start text-white text-sm"
                >
                    <div class="px-10 w-full flex flex-row justify-between leading-relaxed">
                        <div class="flex flex-col">
                            <el-scrollbar class="w-35 h-35">
                                <iframe
                                    src="/revolvermaps.html"
                                    frameborder="0"
                                    style="width: 100%; height: 310px"
                                ></iframe>
                            </el-scrollbar>
                        </div>
                        <div class="flex flex-col">
                            <a class="text-xl mb-3" href="/database">Database</a>
                            <p><a href="/database/dataset">Dataset List</a></p>
                            <p><a href="/database/slice">Slice List</a></p>
                            <p><a href="/database/crustdb_main">CyGraph Conformation List</a></p>
                            <!-- <p><a href="/database/phage">Phage List</a></p>
                            <p><a href="/database/host">Host List</a></p>
                            <p><a href="/database/cluster">Cluster List</a></p>
                            <p><a href="/database/protein">Annotated Protein List</a></p> -->
                            <p><a href="/database/filter">Conformation Filter</a></p>
                        </div>

                        <div class="flex flex-col">
                            <p class="text-xl mb-3">Analysis</p>
                            <p><a href="/analysis/annopipline">Genome Annotation</a></p>
                            <p><a href="/analysis/comparison">Genome Comparison</a></p>
                        </div>
                        <div class="flex flex-col mb-3">
                            <p class="text-xl mb-10"><a href="/workspace">Workspace</a></p>
                            <p class="text-xl"><a href="/download">Download</a></p>
                        </div>
                        <div class="flex flex-col">
                            <p class="text-xl mb-3">Help</p>
                            <p><a href="/tutorial">Tutorial</a></p>
                            <p><a href="/contact">Contact us</a></p>
                        </div>
                    </div>
                    <el-divider />
                    <div>2023 &copy; City University of Hong Kong. All rights reserved.</div>
                </el-footer>
            </div>
        </el-scrollbar>

        <admin v-show="false" />
    </div>
    <el-dialog v-model="dialogVisible" title="Tips" width="30%">
        <span>This is a message</span>

        <template #footer>
            <span class="dialog-footer">
                <el-button @click="dialogVisible = false">Cancel</el-button>
                <el-button type="primary" @click="confirmcookie()">Confirm</el-button>
            </span>
        </template>
    </el-dialog>
</template>

<script setup lang="ts">
// import { ref, onMounted } from 'vue'
import { Opportunity } from '@element-plus/icons-vue'
import { useUserIdGenerator } from '@/utils/userIdGenerator'
import admin from './admin.vue'

const dialogVisible = ref(false)

const descriptionClass = ref('text-gray-500 font-400 pt-1 border-t-1 mb-5 w-70')

const router = useRouter()
// const route = useRoute()

const godatabasae = () => {
    router.push({
        path: '/database',
    })
}

const goDocument = () => {
    router.push({
        path: '/tutorial',
    })
}

const goAnalysis = () => {
    router.push({
        path: '/analysis/annopipline',
    })
}

// onBeforeMount(async () => {
//     const { isCookieExist } = useUserIdGenerator()
//     const CookieExist = ref(isCookieExist())
//     console.log(CookieExist.value)
//     if (!CookieExist.value) {
//         dialogVisible.value = true
//     }
// })

const confirmcookie = () => {
    const { generateUserId, userId } = useUserIdGenerator()
    generateUserId()
    dialogVisible.value = false
    console.log(userId.value)
}
</script>

<style lang="scss" scoped>
:deep(.el-carousel__arrow) {
    background-color: rgb(31 45 61 / 59%);
}

:deep(.el-carousel__indicators--outside button) {
    height: 10px;
    width: 60px;
    background-color: #070708;
}

// :deep(.el-carousel__indicators--outside) {
//     z-index: 500 !important;
//     position: absolute;
//     margin-top: -500px;
// }
</style>
